trigger:
  - none

pool:
  vmImage: 'ubuntu-20.04'

stages:
  - stage: Build
    displayName: Build stage

    jobs:
    - job: Build_Artifacts
      displayName: Build Artifacts
      steps:
        - task: CopyFiles@2
          inputs:
            sourceFolder: $(System.DefaultWorkingDirectory)
            contents: Azure-KeyVault-References/arm/**
            targetFolder: $(Build.ArtifactStagingDirectory)/Azure-KeyVault-References

        - publish: $(Build.ArtifactStagingDirectory)/Azure-KeyVault-References
          artifact: arm

        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: $(workingDirectory)/function
            includeRootFolder: false
            archiveType: zip
            archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            replaceExistingArchive: true

        - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          artifact: function


  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build
    condition: succeeded()

    jobs:
    - deployment: deploy
      displayName: Deploy
      environment: develop
      strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureResourceGroupDeployment@2
                displayName: "Azure ARM Deployment: Key Vault"
                inputs:
                  azureSubscription: azure
                  resourceGroupName: kvrefsdevelop
                  location: 'UK South'
                  csmFile: $(Pipeline.Workspace)/arm/templates/keyvault.json
                  csmParametersFile: $(Pipeline.Workspace)/arm/templates/keyvault.parameters.json
                  overrideParameters:

              - task: AzureResourceGroupDeployment@2
                displayName: "Azure ARM Deployment: Function"
                inputs:
                  azureSubscription: azure
                  resourceGroupName: kvrefsdevelop
                  location: 'UK South'
                  csmFile: $(Pipeline.Workspace)/arm/templates/function.json
                  csmParametersFile: $(Pipeline.Workspace)/arm/templates/function.parameters.json
                  overrideParameters:

              - task: AzureFunctionApp@1
                displayName: 'Azure functions app deploy'
                inputs:
                  azureSubscription: azure
                  appType: functionApp
                  appName: robmarksdevelop
                  package: '$(Pipeline.Workspace)/function/*.zip'
